# order is important, don't change or alternate, otherwise please change all testdata/xxx/judge
# lang: ['*', 'C', 'C++', 'C# 3.0', 'Python 3', 'Scala 2']
# compiler: [, 'g++ -std=c++98 -O2', 'mcs -langversion:3', 'python3', 'scalac -optimise'],
# WT: 0, CE: 1, OLE: 2, MLE: 3, RE: 4, TLE: 5, WA: 6, AC: 7, SAVING: 8, PE: -1,
JUDGE:
    path: 'c:/Users/morris821028/Desktop/github/'
    testdata:
        path: 'c:/Users/morris821028/Desktop/github'
    lang: ['*', 'C']
    compiler_arg: ['none', 'gcc -std=c99 -O2']
    result_message: ['Waiting', 'Compilation Error', 'Output Limit Exceeded', 'Memory Limit Exceeded', 'Runtime Error', 'Time Limit Exceeded', 'Wrong Answer', 'Accepted', 'Uploading...', 'Presentation Error']

# JUDGE_PATH/submission /testdata /source
# JUDGE_PATH: /home/c2014/judgesister/

# MODE: limits user open previous source code & submit problem which not in contest.
CONTEST:
    MODE: false
    SUBMIT_LIMIT: 15
    VALID_CLASS: ["4"]
    VALID_IP: ["::ffff:140.112.16.155", "::ffff:140.112.16.156", "::ffff:140.112.16.158", "::1"]

# DATABASE Setting, MySQL
DATABASE:
    host: '140.112.31.208'
    user: 'c2015'
    password: 'xxxxxxxxxx'
    port: '3306'
    database: 'c2015'

# WEBSITE API HOST
HOST:
    PORT: '8080'
    TITLE: 'Judge Girl'
    IP: '140.112.31.208'
    root: '/'
    testdata: 'https://github.com/JudgeGirl/JG-testdata/blob/master/practice/'
    social:
        youtube: 'https://www.youtube.com/playlist?list=PLOvZ8aEg7xDkpKHk3hAwQxLAlpZ1Q3wKH'
        github: 'https://github.com/pangfengliu/programmingtasks/issues'
        facebook: 'https://www.facebook.com/%E6%89%B9%E6%94%B9%E5%A8%98%E7%B2%89%E7%B5%B2%E5%9C%98-257246016760/timeline/'
        googlesite: 'https://sites.google.com/site/ntucsiec2015/announcement'
    footer:
        text: 'What do you want to do ?'
        license: 'Instructor <a title="劉邦鋒" href="/">Pangfeng Liu</a>, Web designer <a title="許祐程" href="/">Akira</a>, <a title="王盛平" href="/">Peer4321</a>, <a title="曹又霖" href="https://github.com/sinmaplewing">Maplewing</a>, <a title="楊翔雲" href="https://github.com/morris821028">Morris</a>'
# Disqus
Disqus:
    shortname: 'ntucsiecprogramming'

# Privilege
Privilege:
    register_key: 'test'

LOG: 
    path: '/home/c2014/judgesister/file.log'
    level:
        stdout: 'info'
        file: 'debug'

RESOURCE:
    public:
        root: '/home/c2014/judgesister/JudgeResource/public'                        # The path of images, files or scripts related to problems.
        testdata: '/home/c2014/judgesister/JudgeResource/public/downloads/testdata' # The path of testdata which are provided to users.
        announcement: '/home/c2014/judgesister/JudgeResource/announcement'
        problem: '/home/c2014/judgesister/JudgeResource/problem'                    # The path of problem descriptions.
        solution: '/home/c2014/judgesister/JudgeResource/solution'                  # The path of solution descriptions.
        contest: '/home/c2014/judgesister/JudgeResource/contest'                    # The path of contest pages.
    testdata: '/home/c2014/judgesister/JudgeResource/testdata'                      # The path of testdata for problems.
    submission: ''

# Certification
Cert: [
    {
        domain: 'xxxx.xxxx.xxx',
        location: '/etc/letsencrypt/live/xxxxxxxxx.xxxx.xxx' # location of https certification
    }
]
